# theme = "gruvbox_dark_hard"
theme = "gruvbox_dark_soft"

[editor]
scroll-lines = 1
line-number = "relative"
cursorline = true
color-modes = true
true-color = true
bufferline = "multiple"

[editor.cursor-shape]
#insert = "bar"
#normal = "block"
#select = "underline"

[editor.indent-guides]
render = true

[editor.lsp]
auto-signature-help = false
display-messages = true
display-inlay-hints = true

[editor.statusline]
# https://docs.helix-editor.com/editor.html?highlight=statusline#editorstatusline-section
#left = ["mode", "spinner", "file-name", "file-type", "total-line-numbers", "file-encoding"]
#center = []
#right = ["selections", "primary-selection-length", "position", "position-percentage", "spacer", "diagnostics", "workspace-diagnostics", "version-control"]

[keys.normal]
# https://github.com/adamshand/helix-vim/blob/master/config.toml
esc = ["collapse_selection", "keep_primary_selection"]
"*" = ["move_prev_word_start", "move_next_word_end", "search_selection", "global_search"]
"." = "repeat_last_motion"
"^" = "goto_line_start"
"$" = "goto_line_end"
G = "goto_file_end"
Z = { Q = ":quit!", Z = ":write-quit" }
"#" = ["toggle_comments"]
C-a = "goto_line_start"
C-e = "goto_line_end"
# cmd-/ = "toggle_comments"

[keys.insert]
esc = ["collapse_selection", "normal_mode"]
C-a = "goto_line_start"
C-e = "goto_line_end"

[keys.select]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
"$" = "goto_line_end"
"^" = "goto_line_start"
G = "goto_file_end"
C-a = "goto_line_start"
C-e = "goto_line_end"

[editor.file-picker]
# show hidden files
hidden = false
