# logs in ~/.cache/starship
add_newline = true

format = """
$shlvl\
$jobs\
$status\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$docker_context\
$package\
$cmake\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$nix_shell\
$lua\
$line_break\
$username\
$hostname\
$character"""

[shlvl]
disabled = false
symbol ="↕️ "
repeat = "true"
format = "[$symbol]($style) "
#threshold = 2

[jobs]
disabled = false
symbol = "💤 "
threshold = 1
format = "$symbol"

[status]
disabled = false
map_symbol = true
recognize_signal_code = true
#format = '[\[$symbol $common_meaning$signal_name$maybe_int\]]($style) '
format = '[$symbol]($style) '

[directory]
truncation_length = 5
truncation_symbol = "…/"
truncate_to_repo = true

[docker_context]
disabled = false

[golang]
disabled = false

[perl]
disabled = false

[php]
disabled = false

[python]
disabled = false

[ruby]
disabled = false

[rust]
disabled = false

[username]
show_always = true
format = "[$user]($style) @ "

[hostname]
ssh_only = false
trim_at = "."
format = "[$hostname]($style) "
